name: 'Build setup'
description: 'Checks out the code and setups gradle'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: true
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Show java version
      shell: bash
      run: java -version
    - name: Validate checksum gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Gradle cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Gradle cache wrapper
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper